//! felt252-mode Cairo emitter: native field arithmetic, reduce only at outputs.

use crate::circuit::{Circuit, OpKind};

/// Cairo name for a value handle.
fn name(c: &Circuit, id: usize, input_pos: &[usize]) -> String {
    match c.ops[id].kind {
        OpKind::Input => format!("f{}", input_pos[id]),
        OpKind::Const => format!("{}", c.ops[id].val),
        _ => format!("v{}", id),
    }
}

/// Emit a fully-unrolled inner function computing all outputs from n felt252 args.
pub fn emit_felt252(c: &Circuit, fn_name: &str) -> String {
    // map input op-id -> its positional index
    let mut input_pos = vec![0usize; c.ops.len()];
    for (pos, &id) in c.inputs.iter().enumerate() {
        input_pos[id] = pos;
    }

    let n = c.inputs.len();
    let params: Vec<String> = (0..n).map(|i| format!("f{}: felt252", i)).collect();
    let ret: Vec<String> = (0..c.outputs.len()).map(|_| "felt252".to_string()).collect();

    let mut body = String::new();
    for (id, op) in c.ops.iter().enumerate() {
        let expr = match op.kind {
            OpKind::Add => Some(format!("{} + {}", name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Sub => Some(format!("{} - {}", name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Mul => Some(format!("{} * {}", name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            _ => None,
        };
        if let Some(e) = expr {
            body.push_str(&format!("    let v{}: felt252 = {};\n", id, e));
        }
    }

    // outputs: reduce mod q via u128 (all seed bounds are nonneg and < 2^128)
    let mut out_names = vec![];
    for (j, &o) in c.outputs.iter().enumerate() {
        let src = name(c, o, &input_pos);
        body.push_str(&format!("    let r{}_u: u128 = {}.try_into().unwrap();\n", j, src));
        body.push_str(&format!("    let r{}: felt252 = (r{}_u % 12289).into();\n", j, j));
        out_names.push(format!("r{}", j));
    }

    format!(
        "// AUTO-GENERATED by falcon-codegen — DO NOT EDIT.\n\
         // Direct negacyclic NTT (SEED). Replace with fast unrolled NTT in M2.\n\n\
         pub fn {name}({params}) -> ({ret}) {{\n{body}    ({outs})\n}}\n",
        name = fn_name,
        params = params.join(", "),
        ret = ret.join(", "),
        body = body,
        outs = out_names.join(", "),
    )
}
