//! felt252-mode Cairo emitter: native field arithmetic, reduce only where the
//! circuit inserts a Reduce op. Emits an unrolled inner fn + a Span→Array wrapper.

use crate::circuit::{Circuit, OpKind};

fn name(c: &Circuit, id: usize, input_pos: &[usize]) -> String {
    match c.ops[id].kind {
        OpKind::Input => format!("f{}", input_pos[id]),
        OpKind::Const => format!("{}", c.ops[id].val),
        _ => format!("v{}", id),
    }
}

/// Emit the full Cairo module (inner unrolled fn + wrapper) for an n-point NTT.
pub fn emit_module(c: &Circuit, n: usize) -> String {
    let mut input_pos = vec![0usize; c.ops.len()];
    for (pos, &id) in c.inputs.iter().enumerate() {
        input_pos[id] = pos;
    }
    assert_eq!(c.inputs.len(), n);
    assert_eq!(c.outputs.len(), n);

    // ---- inner function ----
    let params: Vec<String> = (0..n).map(|i| format!("f{}: felt252", i)).collect();
    let ret: Vec<String> = (0..n).map(|_| "felt252".to_string()).collect();

    let mut body = String::new();
    for (id, op) in c.ops.iter().enumerate() {
        match op.kind {
            OpKind::Add => body.push_str(&format!(
                "    let v{}: felt252 = {} + {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Sub => body.push_str(&format!(
                "    let v{}: felt252 = {} - {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Mul => body.push_str(&format!(
                "    let v{}: felt252 = {} * {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Reduce => body.push_str(&format!(
                "    let v{id}_u: u128 = {src}.try_into().unwrap();\n    let v{id}: felt252 = (v{id}_u % 12289).into();\n",
                id = id, src = name(c, op.a, &input_pos))),
            _ => {}
        }
    }
    let outs: Vec<String> = c.outputs.iter().map(|&o| name(c, o, &input_pos)).collect();

    // ---- Span -> Array wrapper ----
    let fs: Vec<String> = (0..n).map(|i| format!("f{}", i)).collect();

    format!(
        "// AUTO-GENERATED by falcon-codegen — DO NOT EDIT.\n\
         // Fast negacyclic NTT, size {n}, felt252 mode (lazy per-layer reduction).\n\
         // Output is in bit-reversed order (consistent transform; convolution-valid).\n\n\
         #[inline(never)]\n\
         fn ntt_{n}_inner({params}) -> ({ret}) {{\n{body}    ({outs})\n}}\n\n\
         /// NTT of size {n}: Span<felt252> in [0,q) → Array<felt252> (bit-reversed order).\n\
         #[inline(never)]\n\
         pub fn ntt_{n}(mut input: Span<felt252>) -> Array<felt252> {{\n\
         \x20   let boxed = input.multi_pop_front::<{n}>().expect('need {n} inputs');\n\
         \x20   let [{fs}] = (*boxed).unbox();\n\
         \x20   let ({outs2}) = ntt_{n}_inner({fs});\n\
         \x20   array![{outs2}]\n}}\n",
        n = n,
        params = params.join(", "),
        ret = ret.join(", "),
        body = body,
        outs = outs.join(", "),
        fs = fs.join(", "),
        outs2 = (0..n).map(|j| format!("r{}", j)).collect::<Vec<_>>().join(", "),
    )
}
