//! felt252-mode Cairo emitter: native field arithmetic, reduce only where the
//! circuit inserts a Reduce op. Emits an unrolled inner fn + a Span→Array wrapper.

use crate::circuit::{Circuit, OpKind};
use std::collections::HashMap;

fn name(c: &Circuit, id: usize, input_pos: &[usize]) -> String {
    match c.ops[id].kind {
        OpKind::Input => format!("f{}", input_pos[id]),
        OpKind::Const => format!("{}", c.ops[id].val),
        _ => format!("v{}", id),
    }
}

/// Emit the full Cairo module (inner unrolled fn + wrapper) for an n-point NTT.
pub fn emit_module(c: &Circuit, n: usize) -> String {
    let mut input_pos = vec![0usize; c.ops.len()];
    for (pos, &id) in c.inputs.iter().enumerate() {
        input_pos[id] = pos;
    }
    assert_eq!(c.inputs.len(), n);
    assert_eq!(c.outputs.len(), n);

    // ---- inner function ----
    let params: Vec<String> = (0..n).map(|i| format!("f{}: felt252", i)).collect();
    let ret: Vec<String> = (0..n).map(|_| "felt252".to_string()).collect();

    let mut body = String::new();
    for (id, op) in c.ops.iter().enumerate() {
        match op.kind {
            OpKind::Add => body.push_str(&format!(
                "    let v{}: felt252 = {} + {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Sub => body.push_str(&format!(
                "    let v{}: felt252 = {} - {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Mul => body.push_str(&format!(
                "    let v{}: felt252 = {} * {};\n", id, name(c, op.a, &input_pos), name(c, op.b, &input_pos))),
            OpKind::Reduce => body.push_str(&format!(
                "    let v{id}_u: u128 = {src}.try_into().unwrap();\n    let v{id}: felt252 = (v{id}_u % 12289).into();\n",
                id = id, src = name(c, op.a, &input_pos))),
            _ => {}
        }
    }
    let outs: Vec<String> = c.outputs.iter().map(|&o| name(c, o, &input_pos)).collect();

    // ---- Span -> Array wrapper ----
    let fs: Vec<String> = (0..n).map(|i| format!("f{}", i)).collect();

    format!(
        "// AUTO-GENERATED by falcon-codegen — DO NOT EDIT.\n\
         // Fast negacyclic NTT, size {n}, felt252 mode (lazy per-layer reduction).\n\
         // Output is in bit-reversed order (consistent transform; convolution-valid).\n\n\
         #[inline(never)]\n\
         fn ntt_{n}_inner({params}) -> ({ret}) {{\n{body}    ({outs})\n}}\n\n\
         /// NTT of size {n}: Span<felt252> in [0,q) → Array<felt252> (bit-reversed order).\n\
         #[inline(never)]\n\
         pub fn ntt_{n}(mut input: Span<felt252>) -> Array<felt252> {{\n\
         \x20   let boxed = input.multi_pop_front::<{n}>().expect('need {n} inputs');\n\
         \x20   let [{fs}] = (*boxed).unbox();\n\
         \x20   let ({outs2}) = ntt_{n}_inner({fs});\n\
         \x20   array![{outs2}]\n}}\n",
        n = n,
        params = params.join(", "),
        ret = ret.join(", "),
        body = body,
        outs = outs.join(", "),
        fs = fs.join(", "),
        outs2 = (0..n).map(|j| format!("r{}", j)).collect::<Vec<_>>().join(", "),
    )
}

/// Emit the twiddle table for the LOOPED NTT: `zetas_{n}() -> Array<felt252>`
/// with z[i] = psi^bitrev(i) mod q. The loop logic lives in hand-written Cairo;
/// only this data is generated, so the whole transform is a few KB of code
/// (fits Starknet's contract class-size cap, unlike the unrolled body).
pub fn emit_zetas_table(n: usize) -> String {
    let z = crate::ntt::zetas(n);
    let lits: Vec<String> = z.iter().map(|v| v.to_string()).collect();
    format!(
        "// AUTO-GENERATED by falcon-codegen — DO NOT EDIT.\n\
         // Twiddle table for the looped negacyclic NTT (size {n}).\n\
         // z[i] = psi^bitrev(i) mod q; same convention as the unrolled ntt_{n}.\n\n\
         /// z[i] = psi^bitrev(i) mod q (all < q < 2^14), i in [0,{n}).\n\
         /// z[0] is unused (k starts at 1). u64 so the looped NTT reads it without\n\
         /// a per-block field conversion.\n\
         pub fn zetas_{n}() -> Array<u64> {{\n    array![{lits}]\n}}\n",
        n = n,
        lits = lits.join(", "),
    )
}

/// Name an operand inside a layered chunk: chunk-input → f{pos}, const → literal,
/// otherwise the SSA local v{id} (which must live within the same chunk).
fn lname(c: &Circuit, id: usize, pos_of: &HashMap<usize, usize>) -> String {
    if let Some(&p) = pos_of.get(&id) {
        return format!("f{}", p);
    }
    match c.ops[id].kind {
        OpKind::Const => format!("{}", c.ops[id].val),
        _ => format!("v{}", id),
    }
}

/// Emit the n-point NTT as ONE function PER layer boundary, threading an
/// `Array<felt252>` between them. Each chunk's frame holds ~one layer of ops
/// (≈ n butterflies), so no single Cairo function approaches the USC per-frame
/// offset limit — this is what lets `ntt_512` compose with a second NTT and the
/// verify core in the same compilation unit. Behaviour is identical to
/// `emit_module` (same circuit, same reductions); only the frame layout differs.
pub fn emit_module_layered(c: &Circuit, snapshots: &[Vec<usize>], n: usize) -> String {
    assert_eq!(snapshots.first().unwrap().len(), n);
    assert_eq!(snapshots.last().unwrap().len(), n);
    let num_chunks = snapshots.len() - 1;

    let mut out = String::new();
    out.push_str(&format!(
        "// AUTO-GENERATED by falcon-codegen — DO NOT EDIT.\n\
         // Fast negacyclic NTT, size {n}, felt252 mode (lazy per-layer reduction).\n\
         // Output is in bit-reversed order (consistent transform; convolution-valid).\n\
         // Layered emit: {num_chunks} per-layer functions threaded via Array<felt252>\n\
         // so each frame stays small (USC offset-safe when composed with verify).\n\n",
        n = n,
        num_chunks = num_chunks,
    ));

    for k in 0..num_chunks {
        let ins = &snapshots[k];
        let outs = &snapshots[k + 1];
        // map each chunk-input SSA id to its parameter position
        let mut pos_of: HashMap<usize, usize> = HashMap::new();
        for (p, &id) in ins.iter().enumerate() {
            pos_of.insert(id, p);
        }
        // this chunk owns ops in (max_id(ins), max_id(outs)]
        let start = *ins.iter().max().unwrap();
        let end = *outs.iter().max().unwrap();

        let fs: Vec<String> = (0..n).map(|i| format!("f{}", i)).collect();
        let mut body = String::new();
        for id in (start + 1)..=end {
            let op = &c.ops[id];
            match op.kind {
                OpKind::Add => body.push_str(&format!(
                    "    let v{}: felt252 = {} + {};\n", id, lname(c, op.a, &pos_of), lname(c, op.b, &pos_of))),
                OpKind::Sub => body.push_str(&format!(
                    "    let v{}: felt252 = {} - {};\n", id, lname(c, op.a, &pos_of), lname(c, op.b, &pos_of))),
                OpKind::Mul => body.push_str(&format!(
                    "    let v{}: felt252 = {} * {};\n", id, lname(c, op.a, &pos_of), lname(c, op.b, &pos_of))),
                OpKind::Reduce => body.push_str(&format!(
                    "    let v{id}_u: u128 = {src}.try_into().unwrap();\n    let v{id}: felt252 = (v{id}_u % 12289).into();\n",
                    id = id, src = lname(c, op.a, &pos_of))),
                _ => {}
            }
        }
        let out_names: Vec<String> = outs.iter().map(|&o| lname(c, o, &pos_of)).collect();
        out.push_str(&format!(
            "#[inline(never)]\n\
             fn ntt_{n}_c{k}(mut x: Span<felt252>) -> Array<felt252> {{\n\
             \x20   let boxed = x.multi_pop_front::<{n}>().expect('need {n}');\n\
             \x20   let [{fs}] = (*boxed).unbox();\n\
             {body}    array![{outs}]\n}}\n\n",
            n = n, k = k,
            fs = fs.join(", "),
            body = body,
            outs = out_names.join(", "),
        ));
    }

    // driver: chain the chunks
    let mut driver = String::new();
    driver.push_str(&format!(
        "/// NTT of size {n}: Span<felt252> in [0,q) → Array<felt252> (bit-reversed order).\n\
         #[inline(never)]\n\
         pub fn ntt_{n}(input: Span<felt252>) -> Array<felt252> {{\n\
         \x20   let a0 = ntt_{n}_c0(input);\n",
        n = n,
    ));
    for k in 1..num_chunks {
        driver.push_str(&format!(
            "    let a{k} = ntt_{n}_c{k}(a{prev}.span());\n",
            k = k, prev = k - 1, n = n,
        ));
    }
    driver.push_str(&format!("    a{}\n}}\n", num_chunks - 1));
    out.push_str(&driver);
    out
}
