use falcon::verify::verify_core;
use snforge_std::fs::{FileTrait, read_json};

// Vector generated by reference/gen-vectors from a REAL fn-dsa Falcon-512
// signature (standard SHAKE256). The two forward NTTs (a = NTT(s2),
// b = NTT(mul_hint)) are precomputed by the Rust reference — Cairo's own ntt_512
// is proven equal to that reference in test_ntt512, and compiling two 11k-line
// NTT bodies into one CASM unit hits a compiler frame-offset limit. This test
// exercises the verify core (hint consistency + norm bound) on genuine data.
#[derive(Drop, Serde)]
struct V {
    s2: Array<felt252>,
    pk_ntt: Array<felt252>,
    mul_hint: Array<felt252>,
    msg_point: Array<felt252>,
    a: Array<felt252>,
    b: Array<felt252>,
}

#[test]
fn verify_real_falcon512_signature() {
    let file = FileTrait::new("tests/data/verify512_kat.json");
    let serialized = read_json(@file);
    let mut span = serialized.span();
    let _header = span.pop_front();
    let v: V = Serde::deserialize(ref span).expect('deserialize failed');

    assert!(
        verify_core(
            v.s2.span(),
            v.pk_ntt.span(),
            v.mul_hint.span(),
            v.msg_point.span(),
            v.a.span(),
            v.b.span(),
            512,
        ),
        "real fn-dsa Falcon-512 signature must verify",
    );
}
