use falcon::verify::verify_core;
use snforge_std::fs::{FileTrait, read_json};

// Vector generated by reference/gen-vectors from a REAL fn-dsa Falcon-512
// signature (standard SHAKE256). Here the two forward NTTs (a = NTT(s2),
// b = NTT(mul_hint)) are precomputed by the Rust reference, so this snforge test
// exercises the verify core (hint consistency + norm bound) on genuine data
// without compiling two ntt_512 bodies into one unit (which trips snforge's
// universal-sierra-compiler offset/statement limits).
//
// CANONICAL FULL-VERIFY DEMO: `make verify-exe` runs verify_hint_512 — which
// computes BOTH NTTs itself — on a real signature via `scarb cairo-run`
// (a different compiler path), returning [1] (accepted) at ~143K steps.
// Cairo's ntt_512 is proven equal to the reference in test_ntt512.
#[derive(Drop, Serde)]
struct V {
    s2: Array<felt252>,
    pk_ntt: Array<felt252>,
    mul_hint: Array<felt252>,
    msg_point: Array<felt252>,
    a: Array<felt252>,
    b: Array<felt252>,
}

#[test]
fn verify_real_falcon512_signature() {
    let file = FileTrait::new("tests/data/verify512_kat.json");
    let serialized = read_json(@file);
    let mut span = serialized.span();
    let _header = span.pop_front();
    let v: V = Serde::deserialize(ref span).expect('deserialize failed');

    assert!(
        verify_core(
            v.s2.span(),
            v.pk_ntt.span(),
            v.mul_hint.span(),
            v.msg_point.span(),
            v.a.span(),
            v.b.span(),
            512,
        ),
        "real fn-dsa Falcon-512 signature must verify",
    );
}
