[package]
name = "falcon"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.12.1"

[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.12.1"

[lib]

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
